ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
ALTER SESSION SET CURRENT_SCHEMA = PH2;

-- Dropping role
DROP ROLE RL_NHANVIEN;
DROP ROLE RL_TAICHINH;
DROP ROLE RL_NHANSU;
DROP ROLE RL_TRUONGPHONG;
DROP ROLE RL_QUANLY;
DROP ROLE RL_TRUONGDA;
DROP ROLE RL_GIAMDOC;

-- Declaring role
CREATE ROLE RL_NHANVIEN;
CREATE ROLE RL_TAICHINH;
CREATE ROLE RL_NHANSU;
CREATE ROLE RL_TRUONGPHONG;
CREATE ROLE RL_QUANLY;
CREATE ROLE RL_TRUONGDA;
CREATE ROLE RL_GIAMDOC;

-- CS#1: Nhan vien as role RL_NHANVIEN
GRANT CREATE SESSION TO RL_NHANVIEN; 

CREATE OR REPLACE VIEW V_NHANVIEN 
AS
SELECT MANV, TENNV, PHAI, NGAYSINH, DIACHI, SODT, 
    SYS.DATA_DECRYPT(LUONG, MANV) LUONG, 
    SYS.DATA_DECRYPT(PHUCAP, MANV) PHUCAP, 
    VAITRO, MANQL, PHG, KHUVUC, LINHVUC
FROM NHANVIEN  
WHERE UPPER(MANV) = UPPER(SYS_CONTEXT('USERENV', 'SESSION_USER'));
/

CREATE OR REPLACE VIEW V_PHANCONG 
AS
SELECT * FROM PHANCONG
WHERE UPPER(MANV) = UPPER(SYS_CONTEXT('USERENV', 'SESSION_USER'));
/

GRANT SELECT ON V_NHANVIEN TO RL_NHANVIEN;
GRANT SELECT ON V_PHANCONG TO RL_NHANVIEN;

GRANT UPDATE(NGAYSINH) ON V_NHANVIEN TO RL_NHANVIEN;
GRANT UPDATE(SODT) ON V_NHANVIEN TO RL_NHANVIEN;
GRANT UPDATE(DIACHI) ON V_NHANVIEN TO RL_NHANVIEN;

GRANT SELECT ON PHONGBAN TO RL_NHANVIEN;
GRANT SELECT ON DEAN TO RL_NHANVIEN;
/

-- CS#2: Quan ly as RL_QUANLY
GRANT RL_NHANVIEN TO RL_QUANLY;
/

CREATE OR REPLACE VIEW V_QL_NHANVIEN
AS
SELECT MANV, TENNV, PHAI, NGAYSINH, DIACHI, SODT,
    SYS.DATA_DECRYPT(LUONG, MANV) LUONG, 
    SYS.DATA_DECRYPT(PHUCAP, MANV) PHUCAP,
    VAITRO, MANQL, PHG, KHUVUC, LINHVUC
FROM NHANVIEN 
WHERE MANQL = SYS_CONTEXT('USERENV', 'SESSION_USER') OR MANV = SYS_CONTEXT('USERENV', 'SESSION_USER')
/

GRANT SELECT ON V_QL_NHANVIEN TO RL_QUANLY;

CREATE OR REPLACE VIEW V_QL_PHANCONG
AS
    SELECT PC.MANV, NV.TENNV, PC.MADA, PC.THOIGIAN 
    FROM PHANCONG PC JOIN NHANVIEN NV ON NV.MANV = PC.MANV 
    WHERE PC.MANV = SYS_CONTEXT('USERENV', 'SESSION_USER') OR MANQL = SYS_CONTEXT('USERENV', 'SESSION_USER');
/ 

GRANT SELECT ON V_QL_PHANCONG TO RL_QUANLY;
/

-- CS#3: Truong phong as role RL_TRUONGPHONG
GRANT RL_NHANVIEN TO RL_TRUONGPHONG;

CREATE OR REPLACE VIEW V_TP_NHANVIEN AS
    SELECT MANV, TENNV, PHAI, NGAYSINH, DIACHI, SODT,
    SYS.DATA_DECRYPT(LUONG, MANV) LUONG, 
    SYS.DATA_DECRYPT(PHUCAP, MANV) PHUCAP, 
    VAITRO, MANQL, PHG, KHUVUC, LINHVUC 
    FROM NHANVIEN NV JOIN PHONGBAN ON NV.PHG = MAPB
    WHERE TRPHG = SYS_CONTEXT('USERENV', 'SESSION_USER');
/

GRANT SELECT ON V_TP_NHANVIEN TO RL_TRUONGPHONG;
/

CREATE OR REPLACE VIEW V_TP_PHANCONG 
AS
    SELECT PC.* 
    FROM PH2.V_TP_NHANVIEN NV 
    JOIN PHANCONG PC ON NV.MANV = PC.MANV;
/

-- Trigger to check operations from role
CREATE OR REPLACE TRIGGER TP_INSERT_ON_PHONGBAN
INSTEAD OF INSERT
ON V_TP_PHANCONG 
FOR EACH ROW
DECLARE L_COUNT INT;
BEGIN
    SELECT COUNT(*) INTO L_COUNT
    FROM PH2.V_TP_NHANVIEN 
    WHERE MANV = :NEW.MANV;
        
    IF L_COUNT > 0 THEN
        INSERT INTO PHANCONG VALUES(:NEW.MANV, :NEW.MADA, :NEW.THOIGIAN);
    ELSE
        RAISE_APPLICATION_ERROR(-20001, '');
    END IF;       
END;
/

CREATE OR REPLACE TRIGGER TP_DELETE_ON_PHONGBAN
INSTEAD OF DELETE
ON V_TP_PHANCONG 
FOR EACH ROW
DECLARE L_COUNT INT;
BEGIN
    SELECT COUNT(*) INTO L_COUNT
    FROM PH2.V_TP_NHANVIEN 
    WHERE MANV = :NEW.MANV;
        
    IF L_COUNT > 0 THEN
        DELETE FROM PHANCONG WHERE MANV = :OLD.MANV AND MADA = :OLD.MADA;
    ELSE
        RAISE_APPLICATION_ERROR(-20001, '');
    END IF;
        
END;
/

CREATE OR REPLACE TRIGGER TP_UPDATE_ON_PHONGBAN
INSTEAD OF UPDATE
ON V_TP_PHANCONG 
FOR EACH ROW
DECLARE L_COUNT INT;
BEGIN
    SELECT COUNT(*) INTO L_COUNT
    FROM PH2.V_TP_NHANVIEN 
    WHERE MANV = :NEW.MANV;
        
    IF L_COUNT > 0 THEN
        UPDATE PHANCONG SET MANV = :NEW.MANV, MADA = :NEW.MADA, THOIGIAN = :NEW.THOIGIAN
        WHERE MANV = :OLD.MANV AND MADA = :OLD.MADA;
    ELSE
        RAISE_APPLICATION_ERROR(-20001, '');
    END IF;     
END;
/
GRANT SELECT ON V_TP_NHANVIEN TO RL_TRUONGPHONG;
GRANT INSERT ON V_TP_PHANCONG TO RL_TRUONGPHONG;
GRANT DELETE ON V_TP_PHANCONG TO RL_TRUONGPHONG;
GRANT UPDATE ON V_TP_PHANCONG TO RL_TRUONGPHONG;

-- CS#4: Tai chinh as role RL_TAICHINH
GRANT RL_NHANVIEN TO RL_TAICHINH;
CREATE OR REPLACE VIEW V_ALL_NHANVIEN
AS
    
    SELECT MANV, TENNV, PHAI, NGAYSINH, DIACHI, SODT,
    SYS.DATA_DECRYPT(LUONG, MANV) LUONG, 
    SYS.DATA_DECRYPT(PHUCAP, MANV) PHUCAP,
    VAITRO, MANQL, PHG, KHUVUC, LINHVUC 
    FROM NHANVIEN;
/

GRANT SELECT ON V_ALL_NHANVIEN TO RL_TAICHINH;
GRANT SELECT ON PHANCONG TO RL_TAICHINH;
GRANT UPDATE ON V_ALL_NHANVIEN TO RL_TAICHINH;
/

CREATE OR REPLACE TRIGGER UPDATE_ON_NHANVIEN
INSTEAD OF UPDATE 
ON V_ALL_NHANVIEN
FOR EACH ROW 
BEGIN
    IF :NEW.LUONG <> :OLD.LUONG THEN
        UPDATE NHANVIEN SET LUONG = SYS.DATA_ENCRYPT(UTL_RAW.CAST_TO_RAW(:NEW.LUONG), MANV)
        WHERE MANV = :OLD.MANV;
    END IF;
    
    IF :NEW.PHUCAP <> :OLD.PHUCAP THEN
        UPDATE NHANVIEN SET PHUCAP = SYS.DATA_ENCRYPT(UTL_RAW.CAST_TO_RAW(:NEW.PHUCAP), MANV)
        WHERE MANV = :OLD.MANV;
    END IF;
END;
/

-- CS#5: Nhan su as role RL_NHANSU
GRANT RL_NHANVIEN TO RL_NHANSU;
GRANT INSERT, UPDATE ON PHONGBAN TO RL_NHANSU;
/

CREATE OR REPLACE VIEW V_NS_NHANVIEN
AS
SELECT MANV, TENNV, PHAI, NGAYSINH, DIACHI, SODT, 
    SYS.DATA_DECRYPT(LUONG, MANV) LUONG, 
    SYS.DATA_DECRYPT(PHUCAP, MANV) PHUCAP,
    VAITRO, MANQL, PHG, KHUVUC, LINHVUC 
    FROM NHANVIEN
/

CREATE OR REPLACE TRIGGER NS_INSERT_ON_NHANVIEN
INSTEAD OF INSERT 
ON V_NS_NHANVIEN
FOR EACH ROW 
DECLARE
BEGIN
	INSERT INTO NHANVIEN 
    VALUES(:NEW.MANV, :NEW.TENNV, :NEW.PHAI, :NEW.NGAYSINH,:NEW.DIACHI, :NEW.SODT, '0','0', :NEW.VAITRO, :NEW.MANQL, :NEW.PHG,'123', :NEW.KHUVUC, :NEW.LINHVUC);
END;
/

CREATE OR REPLACE TRIGGER NS_UPDATE_ON_NHANVIEN 
INSTEAD OF UPDATE 
ON V_NS_NHANVIEN 
FOR EACH ROW 
DECLARE
BEGIN
    IF UPDATING('LUONG') OR UPDATING('PHUCAP') THEN
		RAISE_APPLICATION_ERROR(-20001, '');
    ELSE
        UPDATE NHANVIEN SET TENNV=:NEW.TENNV , PHAI=:NEW.PHAI, NGAYSINH=:NEW.NGAYSINH, DIACHI=:NEW.DIACHI, SODT=:NEW.SODT, VAITRO=:NEW.VAITRO, MANQL=:NEW.MANQL, PHG=:NEW.PHG, KHUVUC=:NEW.KHUVUC, LINHVUC=:NEW.LINHVUC
        WHERE :OLD.MANV=MANV;
    END IF;
END;
/

GRANT SELECT ON V_NS_NHANVIEN TO RL_NHANSU;
GRANT INSERT ON V_NS_NHANVIEN TO RL_NHANSU;
GRANT INSERT ON V_NS_NHANVIEN TO RL_NHANSU;
GRANT UPDATE ON V_NS_NHANVIEN TO RL_NHANSU;
/
-- CS#6: Truong de an as role RL_TRUONGDA
GRANT RL_NHANVIEN TO RL_TRUONGDA;

-- CO QUYEN THEM, XOA, SUA TREN QUAN HE DEAN
GRANT SELECT, INSERT, DELETE, UPDATE ON DEAN TO RL_TRUONGDA; 

-- ROLE GIAM DOC
GRANT RL_NHANVIEN TO RL_GIAMDOC;
GRANT SELECT ON NHANVIEN TO RL_GIAMDOC;
GRANT SELECT ON PHANCONG TO RL_GIAMDOC;
GRANT SELECT ANY TABLE TO RL_GIAMDOC;
/

SELECT * FROM DBA_TAB_PRIVS WHERE GRANTEE = 'RL_TAICHINH';