ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
ALTER SESSION SET CURRENT_SCHEMA = PH2;

-- Roles
--CREATE ROLE RL_NHANVIEN;
--CREATE ROLE RL_QUANLY;
--CREATE ROLE RL_TRUONGPHONG;
--CREATE ROLE RL_TAICHINH;
--CREATE ROLE RL_NHANSU;
--CREATE ROLE RL_TRUONGDA;
--CREATE ROLE RL_GIAMDOC;

-- User 001/: GIAMDOC
CREATE USER "001" IDENTIFIED BY 123;
GRANT RL_GIAMDOC TO "001";

-- User 002: Truong de an
CREATE USER "002" IDENTIFIED BY 123;
GRANT RL_TRUONGDA TO "002";

-- User 005: Tai chinh
CREATE USER "005" IDENTIFIED BY 123;
GRANT RL_TAICHINH TO "005";

-- User 010: Nhan su
CREATE USER "010" IDENTIFIED BY 123;
GRANT RL_NHANSU TO "010";

-- User 015: Truong phong
CREATE USER "015" IDENTIFIED BY 123;
GRANT RL_TRUONGPHONG TO "015";

-- User 023: Quan ly
CREATE USER "023" IDENTIFIED BY 123;
GRANT RL_QUANLY TO "023";

-- User 043: Nhan vien
CREATE USER "043" IDENTIFIED BY 123;
GRANT RL_NHANVIEN TO "043";