ALTER SESSION SET CONTAINER=PDB0;
ALTER SESSION SET CURRENT_SCHEMA=PH2;

-- Proc. for dropping tables
CREATE OR REPLACE PROCEDURE DROP_TABLE (P_TABLE IN VARCHAR2)
AS
L_COUNT INT;
BEGIN
    SELECT COUNT(*) INTO L_COUNT
    FROM USER_TABLES WHERE TABLE_NAME = UPPER(P_TABLE);
    
    IF L_COUNT > 0 THEN
        EXECUTE IMMEDIATE 'DROP TABLE ' || P_TABLE;
        DBMS_OUTPUT.PUT_LINE( 'TABLE DROPPPED' );
    ELSE 
        DBMS_OUTPUT.PUT_LINE( 'TABLE DOES NOT EXIST' );
    END IF;
END;
--SET SERVEROUTPUT ON;
/
EXEC DROP_TABLE('SAVE_KEY');
/
EXEC DROP_TABLE('PHANCONG');
/
EXEC DROP_TABLE('DEAN');
/
EXEC DROP_TABLE('PHONGBAN');
/
EXEC DROP_TABLE('NHANVIEN');
/

-- Creating tables
CREATE TABLE NHANVIEN (
    MANV 		VARCHAR(10) PRIMARY KEY,
	TENNV 	    VARCHAR2(60) ,
	PHAI 		VARCHAR2(4),
	NGAYSINH 	DATE,
	DIACHI 	    VARCHAR2(100),
	SODT 		VARCHAR(10)  UNIQUE,
	LUONG 	    RAW(255),
	PHUCAP 	    RAW(255),
	VAITRO 	    VARCHAR2(50),
	MANQL 	    VARCHAR(10),
	PHG 		NUMBER,
    PASSWORD    VARCHAR2(150),
    KHUVUC      VARCHAR2(30),
    LINHVUC     VARCHAR2(50)
);
/

CREATE TABLE PHONGBAN (
	MAPB 		NUMBER PRIMARY KEY,
	TENPB 	    VARCHAR2(60),
	TRPHG 	    VARCHAR(10)
);
/

CREATE TABLE PHANCONG (
	MANV 		VARCHAR(10),
	MADA 		VARCHAR(10),
	THOIGIAN 	DATE,
	CONSTRAINT PK_PC PRIMARY KEY (MANV, MADA)
);
/

CREATE TABLE DEAN (
	MADA 		VARCHAR(10) PRIMARY KEY,
	TENDA 	    VARCHAR2(60) ,
	NGAYBD 	    DATE,
	PHONG 	    NUMBER,
    TRUONGDEAN  VARCHAR(10)
	
);

CREATE TABLE SAVE_KEY(
    MANV 		VARCHAR(10) PRIMARY KEY,
    KEY RAW(255)
); 
/
-- Foreign keys
--MANQL(NHANVIEN) & MANV(NHANVIEN)
ALTER TABLE NHANVIEN
ADD CONSTRAINT FK_NV_NV
  FOREIGN KEY (MANQL)
  REFERENCES NHANVIEN(MANV) ON DELETE CASCADE;
  
--PHG (NHANVIEN) & MAPB(PHONGBAN)
ALTER TABLE NHANVIEN
ADD CONSTRAINT FK_NV_PB
  FOREIGN KEY (PHG)
  REFERENCES PHONGBAN(MAPB) ON DELETE CASCADE;
  
--PHONG (DEAN) & MAPB(PHONGBAN)
ALTER TABLE DEAN
ADD CONSTRAINT FK_DA_PB
  FOREIGN KEY (PHONG)
  REFERENCES PHONGBAN(MAPB) ON DELETE CASCADE;

--TRUONGDEAN (DEAN) & MANV(NHANVIEN)
ALTER TABLE DEAN
ADD CONSTRAINT FK_DA_NV
  FOREIGN KEY (TRUONGDEAN)
  REFERENCES NHANVIEN(MANV) ON DELETE CASCADE;

--MANV (PHANCONG) & MANV (NHANVIEN)
ALTER TABLE PHANCONG
ADD CONSTRAINT FK_PC_NV
  FOREIGN KEY (MANV)
  REFERENCES NHANVIEN(MANV) ON DELETE CASCADE;

 
--MADA (PHANCONG) & MADA (DEAN)
ALTER TABLE PHANCONG
ADD CONSTRAINT FK_PC_DA
  FOREIGN KEY (MADA)
  REFERENCES DEAN(MADA) ON DELETE CASCADE;

