ALTER SESSION SET CONTAINER = PDB0;
--ALTER SESSION SET CURRENT_SCHEMA = PH2;

SELECT * FROM DBA_AUDIT_POLICIES 
WHERE OBJECT_SCHEMA = 'PH2' 
AND OBJECT_NAME = 'PHANCONG';

-- 4A
/*
BEGIN
DBMS_FGA.DROP_POLICY(
  OBJECT_SCHEMA => 'PH2',
  OBJECT_NAME => 'PHANCONG',
  POLICY_NAME => 'AUDIT_POLICY_UPDATE_PC_THOIGIAN');
END;
*/

BEGIN
    DBMS_FGA.ADD_POLICY(
    OBJECT_SCHEMA => 'PH2',
    OBJECT_NAME => 'PHANCONG',
    POLICY_NAME => 'AUDIT_POLICY_UPDATE_PC_THOIGIAN',
    AUDIT_COLUMN => 'THOIGIAN',
    AUDIT_CONDITION => '1=1',
    STATEMENT_TYPES => 'UPDATE');
END;
/

BEGIN
    DBMS_FGA.ENABLE_POLICY(
    OBJECT_SCHEMA => 'PH2',
    OBJECT_NAME => 'PHANCONG',
    POLICY_NAME => 'AUDIT_POLICY_UPDATE_PC_THOIGIAN');
END;
/

-- 4B
/*
BEGIN
DBMS_FGA.DROP_POLICY(
  OBJECT_SCHEMA => 'ATBM',
  OBJECT_NAME => 'NHANVIEN',
  POLICY_NAME => 'LUONG_PHUCAP_AUDIT_POLICY');
END;
*/

BEGIN
    DBMS_FGA.ADD_POLICY(
    OBJECT_SCHEMA => 'PH2',
    OBJECT_NAME => 'NHANVIEN',
    POLICY_NAME => 'AUDIT_POLICY_SELECT_NV_SENSITIVE_DATA',
    AUDIT_COLUMN => 'LUONG, PHUCAP',
    AUDIT_CONDITION => 'MANV != USER',
    STATEMENT_TYPES => 'SELECT');
END;
/

BEGIN
    DBMS_FGA.ENABLE_POLICY(
    OBJECT_SCHEMA => 'PH2',
    OBJECT_NAME => 'NHANVIEN',
    POLICY_NAME => 'AUDIT_POLICY_SELECT_NV_SENSITIVE_DATA');
END;
/

-- 4C
--/*
--BEGIN
--DBMS_FGA.DROP_POLICY(
--  OBJECT_SCHEMA => 'PH2',
--  OBJECT_NAME => 'NHANVIEN',
--  POLICY_NAME => 'AUDIT_POLICY_UPDATE_NV_SENSITVE_DATA');
--END;
--*/

BEGIN 
    DBMS_FGA.ADD_POLICY(
    OBJECT_SCHEMA => 'PH2',
    OBJECT_NAME => 'NHANVIEN',
    POLICY_NAME => 'AUDIT_POLICY_UPDATE_NV_SENSITVE_DATA',
    AUDIT_COLUMN => 'LUONG, PHUCAP',
    AUDIT_CONDITION => 'USER NOT IN (''005'', ''006'', ''007'', ''008'', ''009'')',
    STATEMENT_TYPES => 'UPDATE');
END;
/

BEGIN
    DBMS_FGA.ENABLE_POLICY(
    OBJECT_SCHEMA => 'PH2',
    OBJECT_NAME => 'NHANVIEN',
    POLICY_NAME => 'AUDIT_POLICY_UPDATE_NV_SENSITVE_DATA');
END;
/

CREATE OR REPLACE VIEW V_AUDIT 
AS
    SELECT * 
    FROM UNIFIED_AUDIT_TRAIL
    WHERE FGA_POLICY_NAME  = 'AUDIT_POLICY_UPDATE_PC_THOIGIAN' 
    OR FGA_POLICY_NAME  = 'AUDIT_POLICY_SELECT_NV_SENSITIVE_DATA' 
    OR FGA_POLICY_NAME  = 'AUDIT_POLICY_UPDATE_NV_SENSITVE_DATA';
/

GRANT SELECT ON V_AUDIT TO RL_GIAMDOC;