SELECT VALUE FROM v$option WHERE parameter = 'Oracle Label Security'; 
SELECT status FROM dba_ols_status WHERE name = 'OLS_CONFIGURE_STATUS'; 
/

EXEC LBACSYS.CONFIGURE_OLS; 
EXEC LBACSYS.OLS_ENFORCEMENT.ENABLE_OLS;
/

shutdown IMMEDIATE; 
startup;
/

ALTER SESSION SET CONTAINER=CDB$ROOT;
ALTER USER lbacsys IDENTIFIED BY lbacsys ACCOUNT UNLOCK;
/

select * from v$services; 
SELECT name FROM v$pdbs;


ALTER PLUGGABLE DATABASE PDB0 OPEN READ WRITE;
ALTER SESSION SET CONTAINER=PDB0;
/

SELECT SYS_CONTEXT('USERENV', 'CON_NAME') AS CURRENT_CONTAINER FROM DUAL;

CREATE USER PH2_OLS IDENTIFIED BY 123 CONTAINER = CURRENT; 
GRANT CONNECT, RESOURCE TO PH2_OLS; 
GRANT UNLIMITED TABLESPACE TO PH2_OLS; 
GRANT SELECT ANY DICTIONARY TO PH2_OLS;
---CONN lbacsys/lbacsys; 

--BEGIN SA_SYSDBA.CREATE_POLICY

--( policy_name => 'ACCESS_LOCATIONS', 

--column_name => 'OLS_COLUMN'); 

--END;
/
--DISCONNECT;
GRANT EXECUTE ON SA_COMPONENTS TO PH2_OLS WITH GRANT OPTION; 
GRANT access_locations_dba TO PH2_OLS;
GRANT EXECUTE ON sa_user_admin TO PH2_OLS WITH GRANT OPTION; 
GRANT EXECUTE ON sa_label_admin TO PH2_OLS WITH GRANT OPTION; 
GRANT EXECUTE ON sa_policy_admin TO PH2_OLS WITH GRANT OPTION; 
GRANT EXECUTE ON sa_audit_admin TO PH2_OLS WITH GRANT OPTION; 
GRANT EXECUTE ON sa_session TO PH2_OLS WITH GRANT OPTION; 
GRANT EXECUTE ON DBMS_RLS TO PH2_OLS;
GRANT LBAC_DBA TO PH2_OLS; 
--GRANT CREATE POLICY TO PH2_OLS WITH GRANT OPTION;
GRANT ADMINISTER DATABASE TRIGGER TO PH2_OLS;
GRANT EXECUTE ON sa_sysdba TO PH2_OLS; 
GRANT EXECUTE ON to_lbac_data_label TO PH2_OLS; 
GRANT SELECT, UPDATE, INSERT, DELETE ON PH2.NHANVIEN TO PH2_OLS;
GRANT CREATE USER TO PH2_OLS;
GRANT EXECUTE ON CHAR_TO_LABEL TO PH2_OLS WITH GRANT OPTION;
GRANT CREATE ANY VIEW TO PH2_OLS WITH ADMIN OPTION;

GRANT SELECT ON PH2.V_NHANVIEN TO PH2_OLS;
GRANT CONNECT TO PH2_OLS WITH ADMIN OPTION;

SELECT * FROM dba_users;
SELECT DISTINCT
    grantee,
    privilege
FROM
    dba_sys_privs;

SELECT * FROM DBA_TAB_PRIVS
    WHERE GRANTEE IN (
        SELECT MaNV
        FROM PH2.NHANVIEN
    ) OR GRANTEE LIKE 'RL_%';
    
SELECT grantee, owner, table_name, grantor, privilege, grantable, type FROM DBA_TAB_PRIVS
WHERE GRANTEE IN (SELECT MaNV FROM PH2.NHANVIEN  ) or grantee LIKE 'RL_%';

SELECT grantee, privilege, table_name FROM dba_tab_privs WHERE GRANTEE IN (SELECT MaNV FROM PH2.NHANVIEN  ) or grantee LIKE 'RL_%' ORDER BY grantee 
